import "./globals.css";
import Providers from "./providers";
export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <div className="flex flex-col items-center">{children}</div>
                </Providers>
            </body>
        </html>
    );
}
